### ISSUE TITLE
Stopwatch/Clock Implementation

### ISSUE THREAD

**Issue by timmmerlan** [ev3rt-git/ev3rt-base#6]
Hello,
I am trying to implement a Stopwatch for EV3RT (C++). My first approach was using the time.h library of c++ but this gave me errors during compiling telling me it couldn't find something with "gettimeofday".
I am now looking for a way to implement a stopwatch with the accuracy of ms. Since I am pretty new to EV3RT, I am still a bit confused of different versions, languages, APIs and documentations which of those work together... Some already have something that should work like a stopwatch but I couldn't yet get anything to work (=compile) in my environment (most common error: app.cpp:(.text+0x10c): undefined reference to `detail::us_counter' or replace with another function depending on which approach I tried). Could anyone help me with that?
Thank you in advance!
Tim

**Comment by JakubVanek** [comment]
EV3RT uses the [TOPPERS HRP2](https://www.toppers.jp/en/hrp2-kernel.html) kernel, which is in turn implementing the [μITRON 4.0 API](https://www.tron.org/wp-content/themes/dp-magjam/pdf/specifications/en_US/TEF024-S001-04.03.00_en.pdf).

For this purpose, the `get_tim()` function can be used. From what I've found the resolution of this API is 1 ms and the resolution of the underlying timer on the EV3 is 100 μs.

If a very precise time measurement is needed, maybe some hardware timer in the AM1808 is unused and could be dedicated to this.
