### ISSUE TITLE
Slow color sensor read

### ISSUE THREAD

**Issue by limjh16** [ev3rt-git/ev3rt-base#7]
Hey!
The EV3 color sensor seems to run slower on ev3rt compared to using regular ev3 mindstorms. When I poll the color sensor 10000 times in a loop, it was ~100x faster on ev3 mindstorms compared to ev3rt.

**Comment by YixiaoLi** [comment]
Hello,
Could you upload the test code? For regular EV3, do you mean the LabVIEW software?

**Comment by limjh16** [comment]
Hey,
I do not have the code anymore as I have temporarily switched back to using ev3-g for programming, but it was something simple like:
for(i=0;i++;i<10000) int white = ev3_color_sensor_get_reflect(color_sensor);
and I see the time elapsed by using <time.h>

By regular EV3 mindstorms, I mean ev3-g, the block programming version.

**Comment by JakubVanek** [comment]
I believe the culprit could be that EV3RT does a `uart_sensor_config` syscall each time a sensor is read:
https://github.com/ev3rt-git/ev3rt-hrp2-sdk/blob/16510594d83b1c50d97f868bbf920914621ecdd2/common/ev3api/src/ev3api_sensor.c#L54
Setting the sensor mode should be necessary only when the mode is different from the current one.

Reading a sensor value should theoretically be just a read from a shared memory, which should be very fast.

**Comment by limjh16** [comment]
Hey Jakub,
Thanks for the reply! I would try that ASAP and report if that solves the issue.

**Comment by JakubVanek** [comment]
Hi,

I have created an alternative benchmarking code:
```c
#include "ev3api.h"
#include "app.h"

void main_task(intptr_t exinf) {
    FILE *out;
    SYSTIM t0, t1;

    out = ev3_serial_open_file(EV3_SERIAL_DEFAULT);

    fprintf(out, "initializing...");
    ev3_sensor_config(EV3_PORT_1, COLOR_SENSOR);
    ev3_color_sensor_get_reflect(EV3_PORT_1);

    fprintf(out, "starting benchmark...");
    get_tim(&t0);

    for (size_t i = 0; i < 10000; i++)
        ev3_color_sensor_get_reflect(EV3_PORT_1);

    get_tim(&t1);
    fprintf(out, "stopping benchmark...");

    long dT = t1 - t0;
    fprintf(out, "delta time = %ld ms", dT);

    fclose(out);
}
```
I wouldn't fully trust `time.h` - it is an extra layer on top of the HRP2 kernel syscall layer. This uses the μITRON API instead.

Best regards,

Jakub

**Comment by JakubVanek** [comment]
In comparison, the hacked-together solution for avoiding calls for mode switching is the following:
```c
#include "ev3api.h"
#include "app.h"
#include "platform_interface_layer.h"

uart_data_t *kuarts = NULL;

void init_kuarts() {
    brickinfo_t brickinfo;
    assert(fetch_brick_info(&brickinfo) == E_OK);
    kuarts = brickinfo.uart_sensors;
    assert(kuarts != NULL);    
}

uint8_t read_kuart() {
    uint16_t current = *kuarts[EV3_PORT_1].actual;
    return * (volatile uint8_t *) kuarts[EV3_PORT_1].raw[current];    
}

void main_task(intptr_t exinf) {
    FILE *out;
    SYSTIM t0, t1;

    out = ev3_serial_open_file(EV3_SERIAL_DEFAULT);

    fprintf(out, "initializing...");
    init_kuarts();
    ev3_sensor_config(EV3_PORT_1, COLOR_SENSOR);
    ev3_color_sensor_get_reflect(EV3_PORT_1);

    fprintf(out, "starting benchmark...");
    get_tim(&t0);

    long int running = 0;
    for (size_t i = 0; i < 10000; i++)
        running += read_kuart();

    get_tim(&t1);
    fprintf(out, "stopping benchmark... cumulative value %ld", running);

    long dT = t1 - t0;
    fprintf(out, "delta time = %ld ms", dT);

    fclose(out);
}
```
I had to add a running counter otherwise I think that the value would be discarded by the compiler completely.

**Comment by limjh16** [comment]
Hey @JakubVanek,
Looks like that solved it, thanks! I would be writing a new ev3api_sensor.c soon enough when I have time to configure the color sensor's various modes in the sensor_config function rather than every time I call the "get values" functions.

**Comment by JakubVanek** [comment]
Hi @limjh16,

do you have the measurements comparing the new call and memory access benchmarks available? I would be quite curious how dramatic the impact is.

Best regards,

Jakub
